export const ICONS = {
  VALIDATE: 'pi pi-check-circle',
  SIGNATURE: 'pi pi-file-edit',
  FOLDER: 'pi pi-folder-open',
  FILTER: 'pi pi-filter',
  UPLOAD: 'pi pi-upload',
  MENU: 'pi pi-bars',
  SETTING: 'pi pi-cog',
  LOGOUT: 'pi pi-sign-out',
  LEFT: 'pi pi-chevron-left',
  RIGHT: 'pi pi-chevron-right',
  GOOGLE: 'pi pi-google',
  CLOSE: 'pi pi-times',
  SHIELD: 'pi pi-shield',
  TOKEN: 'pi pi-key',
  USER: 'pi pi-users',
  EYE: 'pi pi-eye',
  EYE_SLASH: 'pi pi-eye-slash',
  SAVE: 'pi pi-save',
  STATUS: 'pi pi-circle',
  MENU_VERTICAL: 'pi pi-ellipsis-v',
  INFO: 'pi pi-info-circle',
  SEND: 'pi pi-send',
  DOWNLOAD: 'pi pi-download',
  CLEAR: 'pi pi-filter-slash',
};
